apiVersion: v1
kind: ConfigMap
metadata:
  name: contacorrente-config
data:
  connection-string: "Data Source=/app/data/contacorrente.db"
  aspnetcore-environment: "Production"
  kafka-bootstrap-servers: "kafka:29092"
  kafka-client-id: "contacorrente-api"
  kafka-consumer-group-id: "contacorrente-consumer-group"